### ISSUE TITLE
Print to PDF

### ISSUE THREAD

**Issue by LifeAdmin-cmd** [lpinner/vscode-chordpro#1]
Hi, I just installed the extension and it works fine so far, but I cant get behind how to convert a song into a pdf. Could someone answer me that please?

**Comment by lpinner** [comment]
Sorry, I never got around to documenting that. Basic steps are:

- Store all chordpro files in a folder somewhere
- Open the top level folder, create a .vscode subfolder and copy [tasks.json](https://github.com/lpinner/vscode-chordpro/blob/master/.vscode/tasks.json) into it (note I've updated this recently)
- Ensure you have [chordpro](https://www.chordpro.org/chordpro/chordpro-reference-implementation/) installed and [configured](https://www.chordpro.org/chordpro/chordpro-configuration/) how you like 
- If using Windows, add the folder that `chordpro.exe` is installed into to your `PATH` user environment variable or edit .vscode/tasks.json and replace `"command": "chordpro"` with `"command": "C:\Full\Path\to\chordpro folder\chordpro"` (I don't use Windows so don't know the real installation path)
- When working on chordpro files, open the top level folder in VS Code, not the individual files
- Convert to PDF using Terminal - Run Task or Terminal - Run Build Task (ctrl-shift-b)

![tabs](https://user-images.githubusercontent.com/4827816/140821769-c87b3faa-2e34-4188-9939-b09414a28a38.png)
